services:
  provide:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: 'your-secret-key'  # Replace with your actual secret key
      DJANGO_DEBUG: 'True'                     # 'True' or 'False' based on your requirement
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'  # List of allowed hosts separated by commas
      DJANGO_DB_PATH: '/app/db.sqlite3'       # Path to your SQLite database
      DJANGO_CORS_ALLOWED_ORIGINS: '*'  # List of allowed origins separated by commas
