# Generated by Django 5.1 on 2025-02-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provide', '0003_license_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
