# Generated by Django 5.1.6 on 2025-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('ease_of_running', models.IntegerField(choices=[(1, '1 - Very Difficult'), (2, '2 - Difficult'), (3, '3 - Neutral'), (4, '4 - Easy'), (5, '5 - Very Easy')])),
                ('ease_of_providing_data', models.IntegerField(choices=[(1, '1 - Very Difficult'), (2, '2 - Difficult'), (3, '3 - Neutral'), (4, '4 - Easy'), (5, '5 - Very Easy')])),
                ('unclear_feedback', models.TextField(blank=True, null=True)),
                ('missing_features', models.TextField(blank=True, null=True)),
                ('additional_suggestions', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
