# Generated by Django 5.1.6 on 2025-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='additional_suggestions',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='ease_of_providing_data',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='ease_of_running',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='missing_features',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='unclear_feedback',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='clarity',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Unclear', 'Unclear'), ('Neutral', 'Neutral')], default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_provide',
            field=models.PositiveIntegerField(choices=[(1, 'Very Difficult'), (2, 'Difficult'), (3, 'Neutral'), (4, 'Easy'), (5, 'Very Easy')], default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_run',
            field=models.PositiveIntegerField(choices=[(1, 'Very Difficult'), (2, 'Difficult'), (3, 'Neutral'), (4, 'Easy'), (5, 'Very Easy')], default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='issues',
            field=models.TextField(default='No issues encountered.'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='suggestions',
            field=models.TextField(default='No suggestions provided.'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='unclear',
            field=models.TextField(default='No unclear points identified.'),
        ),
    ]
