# Generated by Django 5.1.6 on 2025-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_surveyresponse_additional_suggestions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='unclear',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='clarity',
            field=models.CharField(choices=[('Very Clear', 'Very Clear'), ('Clear', 'Clear'), ('Somewhat Clear', 'Somewhat Clear'), ('Unclear', 'Unclear')], default='Clear', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='ease_provide',
            field=models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Neutral', 'Neutral'), ('Difficult', 'Difficult'), ('Very Difficult', 'Very Difficult')], default='Neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='ease_run',
            field=models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Neutral', 'Neutral'), ('Difficult', 'Difficult'), ('Very Difficult', 'Very Difficult')], default='Neutral', max_length=20),
        ),
    ]
