# Generated by Django 5.1.6 on 2025-02-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_surveyresponse_unclear_surveyresponse_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('clarity', 'Clarity'), ('ease', 'Ease of Use'), ('open-ended', 'Open-ended')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='clarity',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='ease_provide',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='ease_run',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question')),
            ],
        ),
    ]
