# Generated by Django 5.1.6 on 2025-03-04 11:18

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_remove_surveyresponse_clarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='clarity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_provide',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ease_run',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
