# Generated by Django 5.2.7 on 2025-10-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyresponse_clarity_surveyresponse_ease_provide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
