name: Deploy to Server

on:
  workflow_dispatch:
  repository_dispatch:
    types: 
      - deploy-trigger # Match the event_type from the previous workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute Remote Commands via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          echo "Executing bash script on remote server..."
          sudo bash /home/vmuser/Development/runner.sh
